---
#set up virtual environment where these need to be installed
#http://docs.ansible.com/ansible/pip_module.html
- name: Falcon | Ensure virtualenv directory exists
  file:
    path: "/{{ app_name }}/virtualenv"
    state: directory

- name: Falcon | Install Falcon
  pip: 
    name: falcon 
    state: present
    virtualenv: /{{ app_name }}/virtualenv

- name: Falcon | Install UWSGI
  pip: 
    name: uwsgi 
    state: present
    virtualenv: /{{ app_name }}/virtualenv

- name: Falcon | Install psycopg2
  pip: 
    name: psycopg2 
    state: present
    virtualenv: /{{ app_name }}/virtualenv