---
- name: PostgresSQL | Install PostgreSQL
  apt: pkg={{ item }} state=installed
  with_items:
    - postgresql-{{ postgresql_version }}
    - postgresql-contrib-{{ postgresql_version }}
    - python3-psycopg2

- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started

- name: PostgreSQL | Create application db 
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  postgresql_db:
    name: "{{ application_db }}"