---
- name: PostgresSQL | Install PostgreSQL
  apt: pkg={{ item }} state=installed
  with_items:
    - postgresql-{{ postgresql_version }}
    - postgresql-contrib-{{ postgresql_version }}
    - python3-psycopg2

- name: PostgreSQL | Ensure PostgreSQL is running
  service:
    name: postgresql
    state: started

- name: PostgreSQL | Create application db 
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  postgresql_db:
    name: "{{ application_db }}"

- name: PostgreSQL | Create PostgreSQL application user
  become: yes
  become_user: "{{ postgresql_admin_user }}"
  postgresql_user:
    db: "{{ application_db }}"
    name: "{{ application_user }}"
    password: "{{ application_user_pass }}"
    state: present
    priv: ALL

- name: PostgreSQL | Update pg_hba.conf
  template:
    src: pg_hba.conf.j2
    dest: "{{postgresql_conf_directory}}/pg_hba.conf"